backend:
  name: github
  branch: master
  repo: 30ozSteak/guard-and-grace

media_folder: static/img
public_folter: /img

collections:
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Team Member", name: "title", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
